ALTER TABLE game ALTER COLUMN player0_id SET NOT NULL;
ALTER TABLE game ALTER COLUMN player1_id SET NOT NULL;
ALTER TABLE game ALTER COLUMN player0_point SET NOT NULL;
ALTER TABLE game ALTER COLUMN player1_point SET NOT NULL;